language: python
python:
- '3.8'
before_install:
- pip install -U pip
install:
- pip install coverage
- pip install coveralls
- pip install -r requirements.txt
script:
- coverage erase
- coverage run -m pytest && coverage html
after_success:
  - coveralls
deploy:
- provider: heroku
  api_key:
    secure: l0EgSfvKv5JEN8zgD2s2GJ/tkUHX7/4MBkjFwJSHoBYye9cnsA2BT+11uVRyzOUj3gwWqmA18vZ59Fry18yJgJOFHBddCZOMKMVTRTuVv94CM0CgJR5b/RzIwPiFkG2K2o2dTevDIfnzaWdUCsFCj2qEbkYOvCkw9oDpTmY3CgPO7js1qjUUinFT3GNzT2sO63YcFj8tQh+VdIpAn9k7EOxX2NskOeTTLM16pGey3cZn4P/GZj8irtkof+5sVNKWOWL0FvAU5vYwfPzlofXK/a/GsB1FIBOj4b22tyEgwtO5toBRcpB2gR+Pw/6Oo4gzqDE9ePnOuCGZyfNrY6JLNGEm4YRs5p9RPgrf/IllEzcI0G3fwzu60sWX6+Thx8jRNGABpbzVQFMxjdMxlhI6mahuh6JvjXnLfP7CXj7Xls80F0Uw7qZa6TSYc0TLAddfY8drJ7RpPyPyHOuQVhp3almk5nvU5f3CEdNA7QziSn0UHsqqPNwd4G2pHAxFIj9Nn1Ds6nyViVS0SKV0v+R6VoHdCV5xI33Qk9mPOsLt5uRXLOA0fmv3fp6XrH3Pi4UaNt1aTdC6F88UAooVlODxHgEgEqwZH+YtWrGNsmyxKY+oZBb/3mxXAr8McKe/lWj04RDDq8d86nL/AKRv9sDe9Nfbd77MLOBkTLTacUuHaVo=
  app: hangry-ateball-staging
  on:
    repo: hangry-ateball/hangry-ateball-be
env:
  global:
  - secure: fx6HAOT+AQVVnUG98zO+oSIBe6qThlBuPAYT6GF6sptcA9yFaza+y9oILDUYs/q8GwQv+iLMqT2BU16NlDMlHSno5vpo9e5hs9XP5ML0GbPIbp6pl+XO5VqdDBJ4NjD23rXF7zEyBjqN+L2NsDa+JFD9T0C64y33t0Qa/+YIWon/hjXFzy/OXDuDCsBJ5eqkMgC9xNUkVnejT/CLNbzCKDeHQs5gN8cdIOAcywWS0AsU/crPutc1txbYPac4nYzzuf4rGLDDyXjLsgthMw/aMqDmlolsGlEVRoZETZuIDlcp1Rm8Lk9QGWPzT0woiYXUluZushPFRgKqCw3oBSC7RgFA4jEQEuWtFNoUYLSIRe/2iZ23mqyU//Bb3hRrjYHiugt9jo8d+qYb5nHkaZOJqY3oK3uN0XpKxdDsdfLDPyWmmAVNZJdt+TdH7Uhnh70QMbFjkJtsP/NkyiA3W4cS2AiiGd8Tv1qa//WoklkAr99L+B4bgX9IMZhlKE+3P0uxA8INJoBh9QaTe+Hu9F3Vx/p6889gENlCjQX7GsByNe2HwxIY2R9CQwH3btSQ+w7PoWzocsK2lTcox0v4CCUN2OQzVZ5Hsb1BgWxeG19/IAO4l89HwOJfcFyT+qTBHBoNEIpSsFnDhjjIkyIXclF6cizRe6C/W1jVCw5zYrN/B4s=
  - secure: NMASd0brVKSGytCwrGH8HXUPu/kyLCWXbuA3eD3v8ULvPsJZOCF4D3UAbVyvYnRBRbOcHK15yt9vHBHeA1iuIErMk19I+526vlSy5SrAdZ7KUkVSeSlitiuN3tzW7uqnyJwRvAHfUyxtr+gJbttniZumNtHiJuWtMrqfg98fFC9Zo1lFkGP3fFCPOuo7oySlypzGFgfvY1zp7zrT19E72RnmzsyAFR+cOjZKGwNZBK8Yx0HTioB30I7PMUf5gBwRWnx+LMlBAsW3nNrGBtZ2T5nt8A7dBaZJZon/v+qwefyZtCy1dM7WQesXrDJFyBcPsWQRcx5EHneIr7OC7ZGK+leFxMTTYJEESguEfIbNqeDIAuYvr7QGi1dv9IPrfFB1Efu/OPyy7+lRFGpILO9tfYwobedjgwbZBHQgzIfn5ajDmSeyUsj3DfvfFv1k3PQLD7WFwo8y4HpDqir6W1vhXy+hu60flrqE+CUcvkW0dDP40pnoPEAm3tm67isJWlWKEHqdADo85Rf80BLuJ46PRk6hgAwYe5ML97W1dhmv8TTn0wk5Op8KSJi9giIRyNiCC2Id+ovFbKxFtIreTdfpTq9TG29OqGD7N7r2cPEFd4q5LRpyodnBty0B0IADdQ6Eu7HXJC5nRHgdcIlSrVDjBtlE6/VKR3TS/JsBebbS6UI=
